version: "3.1"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456a@
      MYSQL_USER: hoangnv
      MYSQL_PASSWORD: 123456a@
    volumes:
      - hfp-volume:/var/lib/mysql
volumes:
  hfp-volume: {}
